### ISSUE TITLE
Unable to boot Ubuntu on Zynq Z7030

### ISSUE THREAD

**Issue by Pranjali-Shinde** [SundanceMultiprocessorTechnology/VCS-1_emc2_ros#2]
I am using vivado version 2017.1 and petalinux 2017.4. Have followed the procedure though the Zynq does not boot! Can you please share the petalinux project inorder to know the problem?

Thank you,

**Comment by pedrombmachado** [comment]
Hi @Pranjali-Shinde,
   This repository is for ROS on the emc2 related questions and not for FIrmware questions.
Merged with request [5](https://github.com/SundanceMultiprocessorTechnology/VCS-1_FM191_FW/issues/5)
